spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:

        - id: books-service
          uri: lb://books
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1

        - id: libs-service
          uri: lb://libs
          predicates:
            - Path=/api/libs/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080


