eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: books
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/books.yml/**
        - id: libs
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/libs/**

management:
  tracing:
    sampling:
      probability: 1.0