spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:

        - id: books-service
          uri: lb://books
          predicates:
            - Path=/api/books/**

        - id: libs-service
          uri: lb://libs
          predicates:
            - Path=/api/libs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
